{% set name = "django-jinja" %}
{% set version = "2.11.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/django-jinja-{{ version }}.tar.gz
  sha256: 47c06d3271e6b2f27d3596278af517bfe2e19c1eb36ae1c0b1cc302d7f0259af

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - django >=1.11,<3.0
    - jinja2 >=3
    - python >=3.6

test:
  imports:
    - django_jinja
    - django_jinja.builtins
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/niwinz/django-jinja
  summary: Jinja2 templating language integrated in Django.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mxr-conda
    - Admax18
